package com.nanshan.app.wsdl;

//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 7.5.0.1
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//------------------------------------------------------------------------


import org.ksoap2.serialization.*;

import java.util.Vector;
import java.util.Hashtable;


public class OQIArrayOfString extends Vector<String> implements KvmSerializable, java.io.Serializable {
    private transient java.lang.Object __source;

    public OQIArrayOfString() {
    }

    public OQIArrayOfString(int initialCapactiy) {
        super(initialCapactiy);
    }

    public OQIArrayOfString(java.util.Collection<String> initialCapactiy) {
        super(initialCapactiy);
    }

    public void loadFromSoap(java.lang.Object inObj, OQIExtendedSoapSerializationEnvelope __envelope) {
        if (inObj == null)
            return;
        __source = inObj;
        SoapObject soapObject = (SoapObject) inObj;
        int size = soapObject.getPropertyCount();
        for (int i0 = 0; i0 < size; i0++) {
            java.lang.Object obj = soapObject.getProperty(i0);
            if (obj != null && obj instanceof AttributeContainer) {
                AttributeContainer j = (AttributeContainer) soapObject.getProperty(i0);
                String j1 = j.toString();
                add(j1);

            }
        }
    }

    public java.lang.Object getSourceObject() {
        return __source;
    }

    @Override
    public java.lang.Object getProperty(int arg0) {
        return this.get(arg0) != null ? this.get(arg0) : SoapPrimitive.NullNilElement;
    }

    @Override
    public int getPropertyCount() {
        return this.size();
    }

    @Override
    public void getPropertyInfo(int index, Hashtable arg1, PropertyInfo info) {
        info.name = "string";
        info.type = PropertyInfo.STRING_CLASS;
        info.namespace = "http://WebXml.com.cn/";
    }

    @Override
    public void setProperty(int arg0, java.lang.Object arg1) {
    }


}