package com.nanshan.app.wsdl;

//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 7.5.0.1
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//------------------------------------------------------------------------


import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class OQIWeatherWebServiceSoap12
{
    interface OQIIWcfMethod
    {
        OQIExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(OQIExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://www.webxml.com.cn/WebServices/WeatherWebService.asmx";

    int timeOut=60000;
    private List< HeaderProperty> httpHeaders= new ArrayList< HeaderProperty>();
    private boolean enableLogging;
    private boolean createClassesForAny = false;


    public List< HeaderProperty> getHttpHeaders()
    {
        return this.httpHeaders;
    }
    
    public boolean getEnableLogging()
    {
        return this.enableLogging;
    }
    
    public void setEnableLogging(boolean value)
    {
        this.enableLogging=value;
    }
    

    
    public boolean getCreateClassesForAny()
    {
        return this.createClassesForAny;
    }
    
    public void setCreateClassesForAny(boolean value)
    {
        this.createClassesForAny=value;
    }
    public OQIWeatherWebServiceSoap12(){}

    public OQIWeatherWebServiceSoap12(String url)
    {
        this.url = url;
    }

    public OQIWeatherWebServiceSoap12(String url,int timeOut)
    {
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                String path=uri.getPath();
                if(uri.getQuery()!=null && uri.getQuery()!="")
                {
                    path+="?"+uri.getQuery();
                }
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, path, timeOut);
            }
            else
            {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }

    protected OQIExtendedSoapSerializationEnvelope createEnvelope()
    {
        OQIExtendedSoapSerializationEnvelope envelope= new OQIExtendedSoapSerializationEnvelope(OQIExtendedSoapSerializationEnvelope.VER12);
        envelope.setEnableLogging( enableLogging);
        envelope.setCreateClassesForAny(createClassesForAny);
    
        return envelope;
    }

    protected java.util.List sendRequest(String methodName,OQIExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport ,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile )throws java.lang.Exception
    {
        if(transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE )
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
        else
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,OQIExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) 
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }

        return null;
    }

    
    public OQIArrayOfString getSupportCity(final String byProvinceName) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OQIArrayOfString)execute(new OQIIWcfMethod()
        {
            @Override
            public OQIExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OQIExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://WebXml.com.cn/", "getSupportCity");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://WebXml.com.cn/";
                __info.name="byProvinceName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(byProvinceName!=null?byProvinceName:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OQIExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (OQIArrayOfString)getResult(OQIArrayOfString.class,__result,"getSupportCityResult",__envelope);
            }
        },"http://WebXml.com.cn/getSupportCity",__profile);
    }
    
    public OQIArrayOfString getSupportProvince() throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OQIArrayOfString)execute(new OQIIWcfMethod()
        {
            @Override
            public OQIExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OQIExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://WebXml.com.cn/", "getSupportProvince");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OQIExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (OQIArrayOfString)getResult(OQIArrayOfString.class,__result,"getSupportProvinceResult",__envelope);
            }
        },"http://WebXml.com.cn/getSupportProvince",__profile);
    }
    
    public org.ksoap2.serialization.SoapObject getSupportDataSet() throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (org.ksoap2.serialization.SoapObject)execute(new OQIIWcfMethod()
        {
            @Override
            public OQIExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OQIExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://WebXml.com.cn/", "getSupportDataSet");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OQIExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (org.ksoap2.serialization.SoapObject)getResult(org.ksoap2.serialization.SoapObject.class,__result,"getSupportDataSetResult",__envelope);
            }
        },"http://WebXml.com.cn/getSupportDataSet",__profile);
    }
    
    public OQIArrayOfString getWeatherbyCityName(final String theCityName) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OQIArrayOfString)execute(new OQIIWcfMethod()
        {
            @Override
            public OQIExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OQIExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://WebXml.com.cn/", "getWeatherbyCityName");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://WebXml.com.cn/";
                __info.name="theCityName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(theCityName!=null?theCityName:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OQIExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (OQIArrayOfString)getResult(OQIArrayOfString.class,__result,"getWeatherbyCityNameResult",__envelope);
            }
        },"http://WebXml.com.cn/getWeatherbyCityName",__profile);
    }
    
    public OQIArrayOfString getWeatherbyCityNamePro(final String theCityName,final String theUserID) throws java.lang.Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (OQIArrayOfString)execute(new OQIIWcfMethod()
        {
            @Override
            public OQIExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                OQIExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://WebXml.com.cn/", "getWeatherbyCityNamePro");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://WebXml.com.cn/";
                __info.name="theCityName";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(theCityName!=null?theCityName:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://WebXml.com.cn/";
                __info.name="theUserID";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(theUserID!=null?theUserID:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(OQIExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (OQIArrayOfString)getResult(OQIArrayOfString.class,__result,"getWeatherbyCityNameProResult",__envelope);
            }
        },"http://WebXml.com.cn/getWeatherbyCityNamePro",__profile);
    }

    protected java.lang.Object execute(OQIIWcfMethod wcfMethod,String methodName,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        OQIExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport,profile);
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    System.out.println("requestDump: "+__httpTransport.requestDump);

                }
                if (__httpTransport.responseDump != null) {
                    System.out.println("responseDump: "+__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }


    protected java.lang.Exception convertToException(org.ksoap2.SoapFault fault,OQIExtendedSoapSerializationEnvelope envelope)
    {
        org.ksoap2.SoapFault newException = fault;
        return newException;
    }
}


